#!/bin/bash
# chkconfig: 345 90 10
# description: auto start simple-whois server
#
name=`basename $0`

case "$1" in
  'start')
    echo "Starting $name" 
    su - ec2-user -c "nohup python /opt/whois.py > /tmp/$name 2>&1 </dev/null &"
    ;;
  'stop')
    echo "stopping simple-whois server..."
    pkill -u ec2-user python
  ;;
esac

