#!/bin/bash
# chkconfig: 345 90 10
# description: auto start simple-whois server
#
case "$1" in
  'start')
    su - ec2-user -c "nohup python /opt/whois.py > /tmp/simple-whois 2>&1 </dev/null &";;
  'stop')
    echo "stopping simple-whois server...";;
esac

